/**
 * deliverableGenerator.js — turns a project analysis into actual client
 * deliverables (proposal, contract, invoice, architecture, slides, package).
 *
 * Each generator returns a Markdown string. Pair with downloadMarkdownFile()
 * or downloadPdfFile() in printableHtml.js to ship to the user as a file.
 *
 * Used by:
 *   • MasterIntelligencePanel.Panel7Actions (action buttons)
 *   • Job Analyzer follow-up deliverables
 *   • Project Builder report stage
 *
 * Backed by REAL data (the analysis the engine produced), never lorem ipsum.
 */

function moneyFmt(n, currency = 'USD') {
  if (n == null) return '—';
  const symbol = currency === 'GBP' ? '£' : currency === 'EUR' ? '€' : '$';
  return `${symbol}${Number(n).toLocaleString()}`;
}

function todayLong() {
  return new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

function dueDateFromTimeline(timeline) {
  if (!timeline) return null;
  const m = timeline.match(/(\d+)\s+(day|week|month)/i);
  if (!m) return null;
  const n = parseInt(m[1], 10);
  const unit = m[2].toLowerCase();
  const ms = unit === 'day' ? 86400000 : unit === 'week' ? 604800000 : 2592000000;
  const d = new Date(Date.now() + n * ms);
  return d.toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
}

// ──────────────────────────────────────────────────────────────────────
// PROPOSAL
// ──────────────────────────────────────────────────────────────────────

export function generateProposalMd(analysis) {
  const lines = [];
  const client = analysis.client || '[Client]';
  const region = analysis.region || 'us-east-1';
  const total = analysis.budget?.fixed ? moneyFmt(analysis.budget.fixed, analysis.budget.currency) : '[To be agreed]';
  const timeline = analysis.timeline || '[To be agreed]';

  lines.push(`# Proposal — AWS Infrastructure Project`);
  lines.push('');
  lines.push(`**To:** ${client}`);
  lines.push(`**Date:** ${todayLong()}`);
  lines.push(`**Project total:** ${total}`);
  lines.push(`**Timeline:** ${timeline}`);
  if (analysis.compliance?.length) {
    lines.push(`**Compliance:** ${analysis.compliance.map((c) => c.label).join(', ')}`);
  }
  lines.push('');

  lines.push(`## Executive summary`);
  lines.push('');
  lines.push(`${analysis.summary}`);
  if (analysis.urgency === 'critical') {
    lines.push('');
    lines.push(`> ⚡ I can begin within **48 hours** given the urgency stated in your brief.`);
  }
  lines.push('');

  if (analysis.compliance?.length) {
    lines.push(`## Compliance approach`);
    lines.push('');
    for (const c of analysis.compliance) lines.push(`- **${c.label}** — addressed via ${c.addServices?.join(', ') || 'controls below'}`);
    lines.push('');
  }

  lines.push(`## Architecture (${analysis.services?.length || 0} services)`);
  lines.push('');
  lines.push(`Region: \`${region}\` · Deployment: \`${(analysis.deploymentMethods || ['terraform']).join('/').toUpperCase()}\``);
  lines.push('');
  lines.push('| Service | Category | Cost note |');
  lines.push('|---|---|---|');
  for (const s of analysis.services || []) {
    lines.push(`| ${s.label} | ${s.category} | ${s.costNote || '—'} |`);
  }
  lines.push('');

  lines.push(`## Approach`);
  lines.push('');
  if (analysis.approach) {
    for (const line of analysis.approach) {
      lines.push(`### ${line.heading}`);
      lines.push('');
      if (Array.isArray(line.body)) {
        line.body.forEach((b, i) => lines.push(`${i + 1}. ${b}`));
      } else {
        lines.push(line.body);
      }
      lines.push('');
    }
  }

  lines.push(`## Deliverables`);
  lines.push('');
  lines.push(`- Working AWS infrastructure in \`${region}\``);
  lines.push(`- Complete ${(analysis.deploymentMethods || ['terraform']).join(' + ').toUpperCase()} source code`);
  lines.push(`- Architecture diagram (PDF)`);
  lines.push(`- Runbook + handover documentation`);
  lines.push(`- 1-hour handover call`);
  lines.push(`- 7 days post-launch support`);
  lines.push('');

  lines.push(`## Investment`);
  lines.push('');
  lines.push(`| Item | Amount |`);
  lines.push(`|---|---:|`);
  lines.push(`| Project total (fixed) | ${total} |`);
  if (analysis.budget?.awsMonthly) {
    lines.push(`| Client monthly AWS spend (estimated) | ≤ ${moneyFmt(analysis.budget.awsMonthly, analysis.budget?.currency)} |`);
  }
  lines.push('');
  lines.push(`Payment terms: 50% deposit on acceptance, 50% on delivery.`);
  lines.push('');

  lines.push(`## Next step`);
  lines.push('');
  lines.push(`Reply "accepted" with PO number — I begin within 48 hours.`);
  lines.push('');
  lines.push('---');
  lines.push('_Generated by AWS Career Launchpad Pro_');
  return lines.join('\n');
}

// ──────────────────────────────────────────────────────────────────────
// CONTRACT
// ──────────────────────────────────────────────────────────────────────

export function generateContractMd(analysis) {
  const client = analysis.client || '[Client Company]';
  const total = analysis.budget?.fixed ? moneyFmt(analysis.budget.fixed, analysis.budget.currency) : '[Fee TBA]';
  const timeline = analysis.timeline || '[Timeline TBA]';

  return [
    `# Services Agreement`,
    '',
    `**Between:** [Your name / company] ("Contractor")`,
    `**And:** ${client} ("Client")`,
    `**Date:** ${todayLong()}`,
    '',
    `## 1. Scope of services`,
    '',
    `Contractor will design, build, and deliver the following AWS infrastructure for the Client:`,
    '',
    ...((analysis.services || []).map((s) => `- ${s.label} (${s.category})`)),
    '',
    analysis.compliance?.length
      ? `Compliance frameworks: ${analysis.compliance.map((c) => c.label).join(', ')}`
      : '',
    '',
    `Deployment method: ${(analysis.deploymentMethods || ['Terraform']).join(' / ').toUpperCase()}`,
    `Target region: ${analysis.region || '[TBA]'}`,
    '',
    `## 2. Timeline`,
    '',
    `${timeline}. Both parties acknowledge milestones may shift by mutual written agreement.`,
    '',
    `## 3. Fees`,
    '',
    `Total fee: ${total}`,
    `Payment terms: 50% on signature, 50% on delivery acceptance.`,
    `Client AWS account costs are the Client's responsibility (estimated ≤ ${analysis.budget?.awsMonthly ? moneyFmt(analysis.budget.awsMonthly, analysis.budget?.currency) : '[TBA]'}/month).`,
    '',
    `## 4. Deliverables`,
    '',
    `- Working infrastructure in Client's AWS account`,
    `- Complete source code (Terraform / CloudFormation as agreed)`,
    `- Architecture diagram`,
    `- Runbook + handover documentation`,
    `- 7 days post-delivery support`,
    '',
    `## 5. Intellectual property`,
    '',
    `On full payment, Client owns all delivered code and documentation.`,
    `Contractor retains the right to re-use generic patterns and snippets.`,
    '',
    `## 6. Confidentiality`,
    '',
    `Each party will keep the other party's confidential information confidential and use it only for performance of this agreement.`,
    '',
    `## 7. Liability`,
    '',
    `Contractor's total liability is capped at fees paid under this agreement.`,
    `Neither party is liable for indirect or consequential losses.`,
    '',
    `## 8. Termination`,
    '',
    `Either party may terminate on 7 days written notice. On termination, Client pays for work completed.`,
    '',
    `## 9. Governing law`,
    '',
    `This agreement is governed by [Your jurisdiction] law.`,
    '',
    `---`,
    `**Signed:**  Contractor _________________________  Date __________`,
    `**Signed:**  Client _________________________  Date __________`,
    '',
    '_Generated by AWS Career Launchpad Pro — review with a lawyer before use._',
  ].filter((l) => l !== null).join('\n');
}

// ──────────────────────────────────────────────────────────────────────
// INVOICE
// ──────────────────────────────────────────────────────────────────────

export function generateInvoiceMd(analysis) {
  const client = analysis.client || '[Client]';
  const total = analysis.budget?.fixed ?? 0;
  const currency = analysis.budget?.currency || 'USD';
  const deposit = Math.round(total * 0.5 * 100) / 100;
  const symbol = currency === 'GBP' ? '£' : currency === 'EUR' ? '€' : '$';
  const due = dueDateFromTimeline('14 days') || '14 days from issue';

  return [
    `# Invoice`,
    '',
    `**Invoice #:** INV-${Date.now().toString().slice(-6)}`,
    `**Date issued:** ${todayLong()}`,
    `**Due:** ${due}`,
    '',
    `**Bill to:** ${client}`,
    '',
    `## Line items`,
    '',
    `| Description | Amount |`,
    `|---|---:|`,
    `| Initial deposit — AWS infrastructure project (50%) | ${symbol}${deposit.toLocaleString()} |`,
    `| **TOTAL DUE** | **${symbol}${deposit.toLocaleString()}** |`,
    '',
    `## Payment details`,
    '',
    `Account name: [Your name]`,
    `Account number: [XXXX XXXX]`,
    `Sort code / IBAN: [XXX]`,
    `Reference: INV-${Date.now().toString().slice(-6)}`,
    '',
    `## Notes`,
    '',
    `- The remaining 50% (${symbol}${deposit.toLocaleString()}) is due on delivery acceptance.`,
    `- Client AWS account costs are billed separately by AWS directly to ${client}.`,
    '',
    '---',
    '_Generated by AWS Career Launchpad Pro_',
  ].join('\n');
}

// ──────────────────────────────────────────────────────────────────────
// ARCHITECTURE (with ASCII diagram)
// ──────────────────────────────────────────────────────────────────────

export function generateArchitectureMd(analysis) {
  const services = analysis.services || [];
  const byCat = {};
  for (const s of services) {
    if (!byCat[s.category]) byCat[s.category] = [];
    byCat[s.category].push(s);
  }

  // Very simple text-diagram per category
  const diagram = [];
  diagram.push('┌────────────────────────────────────────────────────────────┐');
  diagram.push('│  USERS                                                     │');
  diagram.push('└────────────────────────────┬───────────────────────────────┘');
  diagram.push('                             ▼');
  if (byCat.network?.some((s) => s.id === 'route53'))    diagram.push('                       Route 53 (DNS)');
  if (byCat.network?.some((s) => s.id === 'cloudfront')) diagram.push('                       CloudFront (CDN + HTTPS)');
  if (byCat.security?.some((s) => s.id === 'waf'))       diagram.push('                       WAF (firewall)');
  diagram.push('                             ▼');
  if (byCat.network?.some((s) => s.id === 'alb'))        diagram.push('                       Application Load Balancer');
  if (byCat.compute?.length) {
    diagram.push('  ┌──────────────────────────┴──────────────────────────┐');
    diagram.push('  ▼                                                     ▼');
    diagram.push(`  COMPUTE: ${byCat.compute.map((s) => s.label).join(' / ')}`);
  }
  if (byCat.database?.length) {
    diagram.push('                             ▼');
    diagram.push(`  DATABASE: ${byCat.database.map((s) => s.label).join(' / ')}`);
  }
  if (byCat.storage?.length) {
    diagram.push(`  STORAGE:  ${byCat.storage.map((s) => s.label).join(' / ')}`);
  }
  if (byCat.security?.length) {
    diagram.push(`  SECURITY: ${byCat.security.map((s) => s.label).join(' / ')}`);
  }
  if (byCat.monitoring?.length) {
    diagram.push(`  OBSERVABILITY: ${byCat.monitoring.map((s) => s.label).join(' / ')}`);
  }

  const lines = [];
  lines.push(`# Architecture — ${analysis.client || 'Project'}`);
  lines.push('');
  lines.push(`**Region:** ${analysis.region || 'TBA'} · **Date:** ${todayLong()}`);
  lines.push('');
  lines.push('## Diagram');
  lines.push('');
  lines.push('```');
  lines.push(diagram.join('\n'));
  lines.push('```');
  lines.push('');
  lines.push('## Services');
  lines.push('');
  for (const [cat, items] of Object.entries(byCat)) {
    lines.push(`### ${cat.toUpperCase()}`);
    lines.push('');
    for (const s of items) {
      lines.push(`- **${s.label}** — ${s.desc}`);
    }
    lines.push('');
  }
  lines.push('---');
  lines.push('_Generated by AWS Career Launchpad Pro_');
  return lines.join('\n');
}

// ──────────────────────────────────────────────────────────────────────
// SLIDES (Markdown outline)
// ──────────────────────────────────────────────────────────────────────

export function generateSlidesMd(analysis) {
  const lines = [];
  lines.push(`# Slides — ${analysis.client || 'Project'} pitch deck`);
  lines.push('');
  lines.push('## Slide 1 — Title');
  lines.push(`**${analysis.client || 'Client'} — AWS migration & deployment**`);
  lines.push(`Prepared by [Your name] · ${todayLong()}`);
  lines.push('');
  lines.push('## Slide 2 — The challenge');
  lines.push(analysis.summary);
  lines.push('');
  lines.push('## Slide 3 — Proposed architecture');
  lines.push(`${(analysis.services || []).length} AWS services · Region ${analysis.region || 'TBA'}`);
  for (const s of (analysis.services || []).slice(0, 6)) lines.push(`- ${s.label}`);
  lines.push('');
  lines.push('## Slide 4 — Compliance');
  if (analysis.compliance?.length) {
    for (const c of analysis.compliance) lines.push(`- ${c.label}`);
  } else lines.push('- Standard AWS best-practice security baseline');
  lines.push('');
  lines.push('## Slide 5 — Timeline');
  lines.push(`Total: ${analysis.timeline || 'TBA'} · 30% setup · 50% build · 20% test + handover`);
  lines.push('');
  lines.push('## Slide 6 — Investment');
  lines.push(`Project: ${analysis.budget?.fixed ? moneyFmt(analysis.budget.fixed, analysis.budget?.currency) : 'TBA'}`);
  lines.push(`AWS monthly: ≤ ${analysis.budget?.awsMonthly ? moneyFmt(analysis.budget.awsMonthly, analysis.budget?.currency) : 'TBA'}`);
  lines.push('');
  lines.push('## Slide 7 — Next step');
  lines.push(`Approve to begin within 48 hours.`);
  lines.push('');
  lines.push('---');
  lines.push('_Generated by AWS Career Launchpad Pro_');
  return lines.join('\n');
}

// ──────────────────────────────────────────────────────────────────────
// FULL PACKAGE
// ──────────────────────────────────────────────────────────────────────

export function generateFullPackageMd(analysis) {
  return [
    `# Full delivery package — ${analysis.client || 'Project'}`,
    '',
    `Generated ${todayLong()}.`,
    '',
    `This package bundles every deliverable into one document so the client has`,
    `everything they need on day one.`,
    '',
    '---',
    '',
    generateProposalMd(analysis),
    '',
    '---',
    '',
    generateArchitectureMd(analysis),
    '',
    '---',
    '',
    generateContractMd(analysis),
    '',
    '---',
    '',
    generateInvoiceMd(analysis),
    '',
    '---',
    '',
    generateSlidesMd(analysis),
  ].join('\n');
}

export const DELIVERABLE_GENERATORS = {
  proposal:     { label: '📝 Proposal',     fn: generateProposalMd,     filename: 'proposal.md' },
  architecture: { label: '🏗️ Architecture', fn: generateArchitectureMd, filename: 'architecture.md' },
  contract:     { label: '📋 Contract',     fn: generateContractMd,     filename: 'contract.md' },
  invoice:      { label: '🧾 Invoice',      fn: generateInvoiceMd,      filename: 'invoice.md' },
  slides:       { label: '📊 Slides',       fn: generateSlidesMd,       filename: 'slides-outline.md' },
  full:         { label: '📦 Full package', fn: generateFullPackageMd,  filename: 'full-package.md' },
};
