/**
 * reportGenerator.js — turns a recorded session + project deliverables
 * into a portfolio-grade report. Three output channels:
 *
 *   1. Markdown blob — for the Document Center / clipboard / share
 *   2. PDF (via openPrintable) — for portfolio / clients / archives
 *   3. GitHub push — for the project's repo (README + the report + assets)
 *
 * Inputs:
 *   {
 *     session      — a polished session object (from RecorderContext.toPolishedSession)
 *     values       — the wizard's finalValues
 *     account      — { id, alias, region }       (optional)
 *     deliverables — [{ path, content, isBinary }] additional files for GitHub
 *   }
 *
 * Use:
 *   const md = buildSessionReportMarkdown(input);
 *   downloadMarkdown(md, `${slug}.md`);
 *   openPrintable({ markdown: md, title, meta });
 *   await pushSessionReportToGitHub({ token, input, repoName });
 */

import { openPrintable, downloadPdfFile } from './printableHtml.js';
import { pushPortfolioRepo, suggestRepoName } from './githubPush.js';

/**
 * Build a full project / session report as Markdown.
 *
 * Sections:
 *   - Cover / metadata
 *   - Executive summary
 *   - What was built (final values)
 *   - Step-by-step record
 *   - Outcomes + next steps
 *   - Generation footer
 */
export function buildSessionReportMarkdown({ session, values, account, extraSections = [] }) {
  const lines = [];
  lines.push(`# ${session.title || 'Project Report'}`);
  lines.push('');
  lines.push(`**Date:** ${session.date || new Date().toISOString().slice(0, 10)}`);
  if (session.durationMin) lines.push(`**Duration:** ${session.durationMin} minutes`);
  if (account?.id) lines.push(`**AWS account:** ${account.id} (${account.alias || ''})`);
  if (account?.region) lines.push(`**Region:** ${account.region}`);
  lines.push('');

  // Executive summary
  lines.push('## Executive summary');
  lines.push('');
  lines.push(session.summary || 'In-app build session captured automatically.');
  lines.push('');

  // What was built
  if (values && Object.keys(values).length) {
    lines.push('## What was built');
    lines.push('');
    lines.push('| Field | Value |');
    lines.push('|---|---|');
    for (const [k, v] of Object.entries(values)) {
      if (v == null || v === '') continue;
      const display = typeof v === 'object' ? JSON.stringify(v).slice(0, 100) : String(v).slice(0, 200);
      lines.push(`| ${friendlyKey(k)} | ${display} |`);
    }
    lines.push('');
  }

  // Outcomes
  if (session.outcomes?.length) {
    lines.push('## Outcomes');
    lines.push('');
    for (const o of session.outcomes) {
      const icon = o.status === 'done' ? '✅' : o.status === 'pending' ? '🟡' : '❌';
      lines.push(`- ${icon} **${o.label}**${o.note ? ` — ${o.note}` : ''}`);
    }
    lines.push('');
  }

  // Step-by-step record
  if (session.steps?.length) {
    lines.push('## Step-by-step record');
    lines.push('');
    for (const step of session.steps) {
      lines.push(`### Step ${step.n} — ${step.title}`);
      lines.push('');
      if (step.body) { lines.push(step.body); lines.push(''); }
      if (step.tip) { lines.push(`> 💡 **Tip:** ${step.tip}`); lines.push(''); }
      if (step.warning) { lines.push(`> ⚠ **Warning:** ${step.warning}`); lines.push(''); }
      if (step.checkpoint) { lines.push(`> ✓ **Checkpoint:** ${step.checkpoint}`); lines.push(''); }
      if (step.code) { lines.push('```'); lines.push(step.code); lines.push('```'); lines.push(''); }
      lines.push('---');
      lines.push('');
    }
  }

  // Extra sections — provided by the caller (e.g. architecture diagram, screenshots list)
  for (const sec of extraSections) {
    lines.push(`## ${sec.title}`);
    lines.push('');
    lines.push(sec.body);
    lines.push('');
  }

  // Next steps
  if (session.nextSteps?.length) {
    lines.push('## Next steps');
    lines.push('');
    for (const n of session.nextSteps) lines.push(`- ${n}`);
    lines.push('');
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`_Generated by AWS Career Launchpad Pro on ${new Date().toISOString()}._`);

  return lines.join('\n');
}

/**
 * Build a clean default README.md for a new portfolio project repo.
 * If the user provides a custom one in `values.readme`, use that instead.
 */
export function buildProjectReadme({ values, session }) {
  if (values?.readme) return values.readme;

  const lines = [];
  const title = values?.projectName || session?.title || 'AWS Project';
  lines.push(`# ${title}`);
  lines.push('');
  if (values?.summary) { lines.push(`> ${values.summary}`); lines.push(''); }

  lines.push('## Overview');
  lines.push('');
  lines.push(values?.description || 'AWS project built using the AWS Career Launchpad Pro Project Builder wizard.');
  lines.push('');

  if (values?.architecture) {
    lines.push('## Architecture');
    lines.push('');
    lines.push(values.architecture);
    lines.push('');
  }

  if (values?.bucketName || values?.region) {
    lines.push('## Deployment');
    lines.push('');
    if (values.bucketName) lines.push(`- **S3 bucket:** \`${values.bucketName}\``);
    if (values.region)     lines.push(`- **Region:** \`${values.region}\``);
    if (values.distributionId) lines.push(`- **CloudFront distribution:** \`${values.distributionId}\``);
    lines.push('');
  }

  if (values?.lessons) {
    lines.push('## What I learned');
    lines.push('');
    lines.push(values.lessons);
    lines.push('');
  }

  lines.push('## Project report');
  lines.push('');
  lines.push('See [REPORT.md](./REPORT.md) for the full step-by-step session record.');
  lines.push('');

  lines.push('---');
  lines.push('');
  lines.push(`_Generated with AWS Career Launchpad Pro._`);
  return lines.join('\n');
}

// ─────────────────── output channels ───────────────────

/**
 * Trigger a Markdown file download in the browser.
 */
export function downloadMarkdown(markdown, filename) {
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename || 'report.md';
  a.click();
  URL.revokeObjectURL(url);
}

/**
 * Open the print-friendly HTML in a new tab — user prints to PDF from there.
 */
export function openReportPrintable({ markdown, title, meta }) {
  return openPrintable({ markdown, title, meta });
}

/**
 * BF-07: Download a TRUE .pdf file directly to the user's Downloads folder.
 * No popup. No print dialog. Just click → file lands.
 * Uses html2pdf.js under the hood (lazy-loaded).
 */
export async function downloadReportAsPdf({ markdown, title, meta }) {
  return downloadPdfFile({ markdown, title, meta });
}

/**
 * Push a fresh portfolio repo containing README.md + REPORT.md + any
 * deliverables the caller hands us. Returns the public repo URL.
 */
export async function pushSessionReportToGitHub({
  token,
  input,
  repoName: explicitName,
  isPublic = true,
  topics = ['aws', 'portfolio', 'launchpad-pro'],
  extraDeliverables = [],
}) {
  const reportMd = buildSessionReportMarkdown(input);
  const readmeMd = buildProjectReadme(input);
  const repoName = explicitName || suggestRepoName(input.values?.projectName || input.session?.title || 'aws-project');

  const files = [
    { path: 'README.md',  content: readmeMd },
    { path: 'REPORT.md',  content: reportMd },
    { path: '.gitignore', content: defaultGitignore() },
    ...extraDeliverables,
  ];

  return pushPortfolioRepo({
    token,
    repoName,
    description: (input.values?.summary || input.session?.title || 'AWS portfolio project').slice(0, 340),
    isPublic,
    topics,
    files,
  });
}

function defaultGitignore() {
  return [
    'node_modules/',
    '.DS_Store',
    '.env',
    '.env.local',
    '.env.*.local',
    'dist/',
    'build/',
    '*.log',
    '.vscode/',
    '.idea/',
    'coverage/',
    '',
  ].join('\n');
}

function friendlyKey(k) {
  return k
    .replace(/([A-Z])/g, ' $1')
    .replace(/^./, (c) => c.toUpperCase())
    .replace(/[_-]/g, ' ');
}
