/**
 * walkthroughScriptGenerator.js — PJ-02 Full Unified Script Generator.
 *
 * Given a Deep Walkthrough, produces complete end-to-end output in 4
 * formats by concatenating + decorating per-step snippets:
 *
 *   - Console Step-by-Step Guide (Markdown — PDF-ready)
 *   - Full CLI Bash Script (.sh)
 *   - Full CloudFormation Template (.yaml)
 *   - Full Terraform Configuration (.tf)
 *
 * Each generator extracts placeholders, hoists them into a clear
 * variables / parameters section, and adds explanatory comments.
 *
 * Separate from the existing `scriptGenerator.js` (which generates from
 * analyzed service lists) — this one builds from Deep Walkthrough steps.
 */

// Extract UPPER_SNAKE_CASE placeholders that look like user-supplied values
function extractPlaceholders(text) {
  if (!text) return [];
  const matches = text.match(/\b[A-Z][A-Z0-9_]{2,}\b/g) || [];
  // Filter out service names + acronyms — those aren't placeholders
  const noise = new Set([
    'AWS', 'YAML', 'JSON', 'HCL', 'HTTPS', 'HTTP', 'TLS', 'TCP', 'UDP', 'DNS', 'CIDR',
    'AZ', 'AZS', 'VPC', 'IGW', 'NAT', 'ALB', 'NLB', 'IAM', 'ARN', 'OAC', 'OAI',
    'ID', 'GET', 'POST', 'PUT', 'DELETE', 'EOF', 'README', 'NULL', 'TRUE', 'FALSE',
    'IPV4', 'IPV6', 'SSL', 'SSH', 'API', 'CDN', 'OK',
    'CIDRIP', 'CDK', 'SDK', 'CLI', 'CFN', 'TF', 'SAM',
    'TLSV1', 'SNI', 'RFC', 'BGP', 'CRC', 'JIT',
    'EBS', 'EC2', 'S3', 'RDS', 'KMS', 'ECS', 'EKS', 'ECR', 'SQS', 'SNS',
    'WAF', 'CRR', 'SRR', 'PITR', 'DLQ', 'ENI', 'VGW', 'DX', 'TGW',
    'ELB', 'CFN', 'EFS', 'EMR', 'DAX', 'STS', 'XKS', 'SDDC', 'CSI', 'ACL',
  ]);
  return [...new Set(matches.filter((m) => !noise.has(m) && m.length >= 4))];
}

function escapeYaml(s) {
  return String(s).replace(/[\r\n]/g, ' ');
}

function toTitle(s) {
  return String(s).split(/[_\-\s]+/).map((p) => p.charAt(0).toUpperCase() + p.slice(1).toLowerCase()).join('');
}

// ════════════════════════════════════════════════════════════════════
// 1. Console Step-by-Step Guide (Markdown — PDF-ready)
// ════════════════════════════════════════════════════════════════════
export function generateConsoleGuide(w, opts = {}) {
  const region = opts.region;
  const lines = [];
  lines.push(`# ${w.title}`);
  lines.push('');
  lines.push(`> ${w.blurb}`);
  lines.push('');
  lines.push(`**Estimated time:** ${w.estMinutes} minutes  `);
  lines.push(`**Difficulty:** ${w.difficulty}  `);
  lines.push(`**Services used:** ${(w.services || []).join(', ').toUpperCase()}`);
  if (region) lines.push(`**Target AWS region:** ${region} _(picked by AD-01 region suggester)_`);
  lines.push('');
  lines.push(`_Generated by AWS Career Launchpad Pro · PJ-02 Script Generator_`);
  lines.push('');

  if (w.prereqs?.length) {
    lines.push('## Prerequisites');
    lines.push('');
    w.prereqs.forEach((p) => lines.push(`- ${p}`));
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('## Step-by-step guide');
  lines.push('');

  w.steps.forEach((s) => {
    lines.push(`### Step ${s.number} — ${s.title}`);
    lines.push('');
    if (s.what) { lines.push(`**What:** ${s.what}`); lines.push(''); }
    if (s.why)  { lines.push(`**Why it matters:**`); lines.push(''); lines.push(s.why.trim()); lines.push(''); }
    if (s.analogy) { lines.push(`> _Analogy:_ ${s.analogy}`); lines.push(''); }
    if (s.mistakes?.length) {
      lines.push('**Common mistakes to avoid:**');
      lines.push('');
      s.mistakes.forEach((m) => lines.push(`- ⚠ ${m}`));
      lines.push('');
    }
    if (s.how?.console?.length) {
      lines.push('**Console actions:**');
      lines.push('');
      s.how.console.forEach((c, i) => lines.push(`${i + 1}. ${c}`));
      lines.push('');
    }
    lines.push('---');
    lines.push('');
  });

  lines.push('## You\'re done!');
  lines.push('');
  lines.push(`If every step is complete you\'ve successfully built **${w.title}**.`);
  lines.push('');
  lines.push('Don\'t forget to clean up unused resources to avoid ongoing charges.');

  return lines.join('\n');
}

// ════════════════════════════════════════════════════════════════════
// 2. Full CLI Bash Script (.sh)
// ════════════════════════════════════════════════════════════════════
export function generateCliScript(w, opts = {}) {
  const region = opts.region || 'us-east-1';
  const allText = (w.steps || []).map((s) => s.how?.cli || '').join('\n');
  const placeholders = extractPlaceholders(allText);
  const missingSteps = (w.steps || []).filter((step) => !step.how?.cli);

  const lines = [];
  lines.push('#!/usr/bin/env bash');
  lines.push('# ============================================================');
  lines.push(`# ${w.title}`);
  lines.push(`# ${w.blurb}`);
  lines.push('# Generated by AWS Career Launchpad Pro · PJ-02 Script Generator');
  lines.push(`# Target AWS region: ${region}   ← AD-01 Smart Region Suggestion`);
  lines.push('# Review every TODO before running. AWS resources cost money.');
  lines.push('# ============================================================');
  lines.push('');
  lines.push('# Stop on first error, treat unset vars as errors, fail on pipe errors');
  lines.push('set -euo pipefail');
  lines.push('');

  if (placeholders.length || missingSteps.length) {
    lines.push('echo "DEPLOYMENT BLOCKED: this walkthrough export is an incomplete draft." >&2');
    lines.push(`echo "Missing CLI steps: ${missingSteps.map((step) => step.number).join(', ') || 'none'}; placeholders: ${placeholders.join(', ') || 'none'}" >&2`);
    lines.push('echo "Resolve every item and remove this gate only after review." >&2');
    lines.push('exit 1');
    lines.push('');
  }

  if (placeholders.length > 0) {
    lines.push('# ---------- VARIABLES (edit these before running) ----------');
    placeholders.forEach((p) => {
      lines.push(`${p}="REPLACE_WITH_YOUR_VALUE"   # TODO: set this`);
    });
    lines.push('# -----------------------------------------------------------');
    lines.push('');
  }

  lines.push('# Common AWS settings');
  lines.push(`AWS_REGION="\${AWS_REGION:-${region}}"   # picked by AD-01 region suggester · override via export AWS_REGION=us-east-1`);
  lines.push('echo "Running in region: $AWS_REGION"');
  lines.push('');

  w.steps.forEach((s) => {
    lines.push('# ============================================================');
    lines.push(`# Step ${s.number} — ${s.title}`);
    lines.push(`# ${(s.what || '').replace(/[\r\n]/g, ' ')}`);
    lines.push('# ============================================================');
    if (s.mistakes?.length) {
      lines.push('# Heads up:');
      s.mistakes.forEach((m) => lines.push(`#   ⚠ ${m.replace(/[\r\n]/g, ' ')}`));
    }
    lines.push('');
    if (s.how?.cli) {
      lines.push(s.how.cli.trim());
    } else {
      lines.push(`# (no CLI snippet for this step — perform via console:`);
      (s.how?.console || []).forEach((c) => lines.push(`#   • ${c}`));
      lines.push(')');
    }
    lines.push('');
    lines.push(`echo "✓ Step ${s.number} done"`);
    lines.push('');
  });

  lines.push('# ============================================================');
  lines.push('echo "🎉 All steps complete — verify in the AWS Console!"');
  lines.push('# ============================================================');

  return lines.join('\n');
}

// ════════════════════════════════════════════════════════════════════
// 3. Full CloudFormation Template (.yaml)
// ════════════════════════════════════════════════════════════════════
export function generateCfnTemplate(w, opts = {}) {
  const region = opts.region;
  const allCfn = (w.steps || []).map((s) => s.how?.cfn || '').join('\n');
  const placeholders = extractPlaceholders(allCfn);
  const missingSteps = (w.steps || []).filter((step) => !step.how?.cfn);
  const blocked = placeholders.length > 0 || missingSteps.length > 0;

  const lines = [];
  lines.push('AWSTemplateFormatVersion: "2010-09-09"');
  lines.push(`Description: |`);
  lines.push(`  ${w.title}`);
  lines.push(`  ${w.blurb}`);
  lines.push('  Generated by AWS Career Launchpad Pro · PJ-02 Script Generator.');
  if (region) lines.push(`  Target AWS region: ${region} (AD-01 suggested — deploy with: aws cloudformation deploy --region ${region} ...)`);
  lines.push('  REVIEW + EDIT before deploying — assembled by concatenating per-step snippets.');
  lines.push('');

  if (placeholders.length > 0 || blocked) {
    lines.push('Parameters:');
    placeholders.forEach((p) => {
      lines.push(`  ${toTitle(p)}:`);
      lines.push(`    Type: String`);
      lines.push(`    Description: "Replace with your ${p} value"`);
      lines.push(`    Default: "REPLACE_${p}"`);
    });
    if (blocked) {
      lines.push('  ConfirmGeneratedArtifactComplete:');
      lines.push('    Type: String');
      lines.push('    Default: "BLOCKED"');
      lines.push('    AllowedValues: ["BLOCKED", "REVIEWED"]');
      lines.push('    Description: "Set REVIEWED only after implementing every missing step and placeholder."');
    }
    lines.push('');
  }

  if (blocked) {
    lines.push('Rules:');
    lines.push('  GeneratedArtifactSafetyGate:');
    lines.push('    Assertions:');
    lines.push('      - Assert: !Equals [!Ref ConfirmGeneratedArtifactComplete, "REVIEWED"]');
    lines.push(`        AssertDescription: "Incomplete walkthrough export. Missing CFN steps: ${missingSteps.map((step) => step.number).join(', ') || 'none'}."`);
    lines.push('');
  }

  lines.push('# ============================================================');
  lines.push('# Resources — merged from each step\'s CFN snippet');
  lines.push('# Note: some snippets in the Deep Walkthrough are illustrative');
  lines.push('# fragments. Review references + cross-stack dependencies before');
  lines.push('# running `aws cloudformation deploy`.');
  lines.push('# ============================================================');
  lines.push('Resources:');
  lines.push('');

  w.steps.forEach((s) => {
    lines.push(`  # ----- Step ${s.number}: ${escapeYaml(s.title)} -----`);
    lines.push(`  # ${escapeYaml(s.what || '')}`);
    if (s.how?.cfn) {
      const snippet = s.how.cfn.trim();
      const cleaned = snippet
        .replace(/^Resources:\s*\n?/gmi, '')
        .replace(/^Parameters:\s*\n?/gmi, '# (parameters hoisted to top)\n');
      const linesIn = cleaned.split('\n');
      linesIn.forEach((line) => {
        if (line.trim().length === 0) { lines.push(''); return; }
        lines.push('  ' + line);
      });
    } else {
      lines.push(`  # (no CloudFormation snippet for this step — manual / CLI only)`);
    }
    lines.push('');
  });

  lines.push('Outputs:');
  lines.push('  Note:');
  lines.push('    Description: "Assembled from per-step snippets — verify references before deploy"');
  lines.push('    Value: "REVIEW + VALIDATE before deploy"');

  return lines.join('\n');
}

// ════════════════════════════════════════════════════════════════════
// 4. Full Terraform Configuration (.tf)
// ════════════════════════════════════════════════════════════════════
export function generateTerraform(w, opts = {}) {
  const region = opts.region || 'us-east-1';
  const allTf = (w.steps || []).map((s) => s.how?.tf || '').join('\n');
  const placeholders = extractPlaceholders(allTf);
  const missingSteps = (w.steps || []).filter((step) => !step.how?.tf);
  const blocked = placeholders.length > 0 || missingSteps.length > 0;

  const lines = [];
  lines.push('# ============================================================');
  lines.push(`# ${w.title}`);
  lines.push(`# ${w.blurb}`);
  lines.push('# Generated by AWS Career Launchpad Pro · PJ-02 Script Generator');
  lines.push(`# Target AWS region: ${region}   ← AD-01 Smart Region Suggestion`);
  lines.push('# REVIEW + EDIT before terraform apply — generated by concatenating per-step snippets.');
  lines.push('# ============================================================');
  lines.push('');

  if (blocked) {
    lines.push('# DEPLOYMENT BLOCKED: incomplete walkthrough export.');
    lines.push('variable "confirm_generated_artifact_complete" {');
    lines.push('  type    = bool');
    lines.push('  default = false');
    lines.push('}');
    lines.push('resource "terraform_data" "generation_safety_gate" {');
    lines.push('  lifecycle {');
    lines.push('    precondition {');
    lines.push('      condition = var.confirm_generated_artifact_complete');
    lines.push(`      error_message = "Resolve missing Terraform steps (${missingSteps.map((step) => step.number).join(', ') || 'none'}) and all placeholders before apply."`);
    lines.push('    }');
    lines.push('  }');
    lines.push('}');
    lines.push('');
  }
  lines.push('terraform {');
  lines.push('  required_version = ">= 1.5.0"');
  lines.push('  required_providers {');
  lines.push('    aws = { source = "hashicorp/aws", version = "~> 5.0" }');
  lines.push('  }');
  lines.push('}');
  lines.push('');
  lines.push('# Primary region — picked by AD-01 region suggester · override via TF_VAR_aws_region or -var');
  lines.push('variable "aws_region" {');
  lines.push('  type    = string');
  lines.push(`  default = "${region}"`);
  lines.push('}');
  lines.push('');
  lines.push('provider "aws" {');
  lines.push('  region = var.aws_region');
  lines.push('}');
  lines.push('');

  if (placeholders.length > 0) {
    lines.push('# ----------------------------------------------------------');
    lines.push('# Variables — set these in terraform.tfvars or via -var flags');
    lines.push('# ----------------------------------------------------------');
    placeholders.forEach((p) => {
      lines.push(`variable "${p.toLowerCase()}" {`);
      lines.push(`  type        = string`);
      lines.push(`  description = "Replace with your ${p} value"`);
      lines.push(`  default     = "REPLACE_${p}"`);
      lines.push('}');
      lines.push('');
    });
  }

  w.steps.forEach((s) => {
    lines.push('# ============================================================');
    lines.push(`# Step ${s.number} — ${s.title}`);
    lines.push(`# ${s.what || ''}`);
    lines.push('# ============================================================');
    if (s.mistakes?.length) {
      lines.push('# Heads up:');
      s.mistakes.forEach((m) => lines.push(`#   ⚠ ${m.replace(/[\r\n]/g, ' ')}`));
    }
    lines.push('');
    if (s.how?.tf) {
      lines.push(s.how.tf.trim());
    } else {
      lines.push(`# (no Terraform snippet for this step — see CLI or Console)`);
    }
    lines.push('');
  });

  return lines.join('\n');
}

// ════════════════════════════════════════════════════════════════════
// File metadata per format
// ════════════════════════════════════════════════════════════════════
export const SCRIPT_FORMATS = [
  {
    id: 'console',
    label: 'Console Step-by-Step Guide',
    extension: 'md',
    mime: 'text/markdown',
    language: 'markdown',
    icon: '📋',
    description: 'Printable Markdown guide. Every step with WHAT, WHY, analogy, mistakes, and console actions. Convert to PDF in any reader.',
    generate: generateConsoleGuide,
  },
  {
    id: 'cli',
    label: 'Full CLI Bash Script',
    extension: 'sh',
    mime: 'text/x-shellscript',
    language: 'bash',
    icon: '💻',
    description: 'Assembled Bash draft with safety gates when any command or value is missing. Review before execution.',
    generate: generateCliScript,
  },
  {
    id: 'cfn',
    label: 'Full CloudFormation Template',
    extension: 'yaml',
    mime: 'application/x-yaml',
    language: 'yaml',
    icon: '☁',
    description: 'Assembled CloudFormation draft. Incomplete steps and placeholders block deployment until reviewed.',
    generate: generateCfnTemplate,
  },
  {
    id: 'tf',
    label: 'Full Terraform Configuration',
    extension: 'tf',
    mime: 'text/x-hcl',
    language: 'hcl',
    icon: '🔧',
    description: 'Assembled Terraform draft. Incomplete steps and placeholders block apply until reviewed.',
    generate: generateTerraform,
  },
];

// ════════════════════════════════════════════════════════════════════
// Download helper (Blob → click anchor)
// ════════════════════════════════════════════════════════════════════
export function downloadScript(filename, content, mime) {
  try {
    const blob = new Blob([content], { type: mime + ';charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 30000);
  } catch (err) {
    console.error('Download failed:', err);
    throw err;
  }
}
