import { Bookmark, RotateCcw } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageHeader } from '../components/common/PageHeader.jsx';
import { useExam } from '../context/ExamContext.jsx';
import { questionsForCert } from '../data/questionBank.js';

export default function SAAReview(){const {getCertState,toggleBookmark}=useExam();const state=getCertState('saa-c03');const byId=new Map(questionsForCert('saa-c03').map(q=>[q.id,q]));const tally={};for(const a of state.attempts||[])for(const r of a.questionResults||[]){const t=tally[r.qId]||{attempts:0,incorrect:0,last:a.at};t.attempts++;if(!r.isCorrect)t.incorrect++;t.last=a.at;tally[r.qId]=t}const mistakes=Object.entries(tally).filter(([,v])=>v.incorrect).sort((a,b)=>b[1].incorrect-a[1].incorrect);const bookmarks=Object.keys(state.bookmarks||{});
return <div className="space-y-6"><PageHeader eyebrow="Review" title="Mistakes bank & saved questions" subtitle="Incorrect answers remain in revision until repeated success demonstrates mastery." icon={RotateCcw}/><div className="grid gap-4 lg:grid-cols-2"><List title="Mistakes bank" empty="No mistakes recorded yet. Complete a practice session to build your revision queue." ids={mistakes.map(([id])=>id)} byId={byId} detail={id=>`${tally[id].incorrect} incorrect of ${tally[id].attempts} attempts`}/><List title="Bookmarked questions" empty="No bookmarked questions yet. Save any question while studying or reviewing." ids={bookmarks} byId={byId} detail={id=>state.bookmarks[id]?.revision?'Revision priority':'Saved for later'} onRemove={id=>toggleBookmark('saa-c03',id)}/></div><div className="flex flex-wrap gap-2"><Link className="btn btn-primary" to="/exam/saa-c03/run/review">Practice adaptive review</Link><Link className="btn btn-ghost" to="/exam/saa-c03">Previous exams and domain detail</Link></div></div>}
function List({title,empty,ids,byId,detail,onRemove}){return <section className="surface rounded-2xl p-5"><h2 className="font-extrabold">{title}</h2>{!ids.length?<p className="mt-3 text-sm text-muted">{empty}</p>:<ul className="mt-3 divide-y divide-[var(--border)] max-h-[620px] overflow-auto">{ids.map(id=>{const q=byId.get(id);if(!q)return null;return <li key={id} className="py-3"><div className="flex gap-3"><div className="flex-1"><p className="text-sm font-semibold leading-relaxed">{q.q}</p><p className="mt-1 text-[11px] text-muted">{detail(id)} · {(q.service||[]).slice(0,3).join(', ')}</p></div>{onRemove&&<button onClick={()=>onRemove(id)} aria-label="Remove bookmark" className="text-electric"><Bookmark size={16} className="fill-current"/></button>}</div></li>})}</ul>}</section>}
