import { motion } from 'framer-motion';
import {
  Bolt, Check, ClipboardCopy, FileText, Save, Sparkles, Wand2, X,
} from 'lucide-react';
import { useMemo, useState } from 'react';
import { useApp } from '../../context/AppContext.jsx';
import { useFreelance } from '../../context/FreelanceContext.jsx';
import { useToast } from '../../context/ToastContext.jsx';
import { PROPOSAL_TEMPLATES } from '../../data/proposalTemplates.js';
import { analyzeJobDescription, generateProposal } from '../../lib/freelanceEngine.js';
import { cn } from '../../lib/utils.js';

/**
 * Paste a job description → AI extracts requirements → generates a tailored
 * winning proposal you can edit + copy + save as a new tracker entry.
 */
export function ProposalBuilder() {
  const { profile } = useApp();
  const { addProposal } = useFreelance();
  const toast = useToast();
  const [jd, setJd] = useState('');
  const [templateId, setTemplateId] = useState('');
  const [generated, setGenerated] = useState(null);
  const [edited, setEdited] = useState('');

  const analysis = useMemo(() => analyzeJobDescription(jd), [jd]);

  const onAnalyze = () => {
    if (!jd.trim()) {
      toast.warning('Paste a job description first');
      return;
    }
    const useId = templateId || analysis?.recommendedTemplateId;
    const out = generateProposal({ jd, profile, templateId: useId, jobAnalysis: analysis });
    setGenerated(out);
    setEdited(out.fullText);
    if (!templateId) setTemplateId(out.template.id);
  };

  const onCopy = async () => {
    try {
      await navigator.clipboard.writeText(edited);
      toast.success('Proposal copied — paste into Upwork/LinkedIn');
    } catch {
      toast.error('Could not copy — select + copy manually');
    }
  };

  const onSaveToTracker = () => {
    if (!generated) return;
    addProposal({
      platform: 'Upwork',
      clientName: analysis?.clientName || '',
      jobTitle: analysis?.projectTitle || '',
      budget: analysis?.budget ? `${analysis.budget.currency} ${analysis.budget.low}${analysis.budget.high ? '–' + analysis.budget.high : ''}` : '',
      status: 'sent',
      body: edited,
      notes: 'Generated by Proposal Builder.',
    });
    toast.success('Saved to tracker — set status when client replies');
  };

  return (
    <div className="grid gap-4 lg:grid-cols-2">
      {/* INPUT */}
      <div className="space-y-3">
        <div className="surface rounded-2xl p-4 sm:p-5">
          <div className="flex items-center gap-2 mb-3">
            <FileText size={14} className="text-aws-orange" />
            <h3 className="text-[11px] font-extrabold uppercase tracking-widest">Paste job description</h3>
          </div>
          <textarea
            value={jd}
            onChange={(e) => setJd(e.target.value)}
            placeholder={`Paste the Upwork/LinkedIn job post here.\n\nExample: "We need an AWS engineer to migrate our MySQL database to RDS Aurora with minimal downtime. Budget: $4000-6000."`}
            rows={11}
            className="w-full bg-[var(--card-2)] border border-token rounded-xl p-3 text-sm leading-relaxed focus-ring focus:border-aws-orange resize-y font-mono"
          />
          <div className="mt-3 flex flex-wrap items-center gap-2">
            <button onClick={onAnalyze} className="btn btn-primary">
              <Wand2 size={14} /> Analyse + generate
            </button>
            <select
              value={templateId}
              onChange={(e) => setTemplateId(e.target.value)}
              className="bg-[var(--card-2)] border border-token rounded-lg px-2 py-2 text-xs font-semibold"
            >
              <option value="">Auto-pick template</option>
              {PROPOSAL_TEMPLATES.map((t) => (
                <option key={t.id} value={t.id}>{t.icon} {t.type}</option>
              ))}
            </select>
          </div>
        </div>

        {/* Analysis card */}
        {analysis && (
          <motion.div
            initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }}
            className="surface rounded-2xl p-4 sm:p-5"
          >
            <div className="flex items-center gap-2 mb-3">
              <Sparkles size={14} className="text-aws-orange" />
              <h3 className="text-[11px] font-extrabold uppercase tracking-widest">AI analysis</h3>
            </div>
            <dl className="grid grid-cols-2 gap-x-3 gap-y-2 text-xs">
              <Field k="Project" v={analysis.projectTitle} />
              <Field k="Client" v={analysis.clientName || '(not detected)'} />
              <Field k="Pain point" v={analysis.painPoint?.slice(0, 100) + (analysis.painPoint?.length > 100 ? '…' : '')} wide />
              <Field k="Budget"
                v={analysis.budget
                  ? `${analysis.budget.currency} ${analysis.budget.low.toLocaleString()}${analysis.budget.high ? '–' + analysis.budget.high.toLocaleString() : ''}`
                  : '(not detected)'} />
              <Field k="Pricing" v={analysis.isHourly ? 'Hourly' : 'Fixed'} />
              <Field k="Seniority" v={analysis.level} />
              <Field k="Services" v={analysis.services?.join(', ') || '(none detected)'} wide />
              <Field k="Recommended" v={PROPOSAL_TEMPLATES.find((t) => t.id === analysis.recommendedTemplateId)?.type || '—'} wide />
            </dl>
          </motion.div>
        )}
      </div>

      {/* OUTPUT */}
      <div className="space-y-3">
        <div className="surface rounded-2xl p-4 sm:p-5 min-h-[280px]">
          {!generated ? (
            <div className="h-full grid place-items-center text-center text-muted py-10">
              <div>
                <Bolt size={28} className="mx-auto mb-2 text-aws-orange" />
                <div className="text-sm font-bold">Generate a proposal</div>
                <p className="text-xs mt-1">Paste a JD on the left, then click Analyse + generate.</p>
              </div>
            </div>
          ) : (
            <>
              <div className="flex items-center justify-between gap-2 mb-3">
                <div className="text-[11px] font-extrabold uppercase tracking-widest text-aws-orange flex items-center gap-1.5">
                  <Sparkles size={11} /> {generated.template.icon} {generated.template.type}
                </div>
                <div className="flex items-center gap-1">
                  <button onClick={onCopy} className="btn btn-ghost !text-[11px] !py-1.5">
                    <ClipboardCopy size={11} /> Copy
                  </button>
                  <button onClick={onSaveToTracker} className="btn btn-ghost !text-[11px] !py-1.5">
                    <Save size={11} /> Save to tracker
                  </button>
                </div>
              </div>
              <textarea
                value={edited}
                onChange={(e) => setEdited(e.target.value)}
                rows={20}
                className="w-full bg-[var(--card-2)] border border-token rounded-xl p-3 text-[13px] leading-relaxed focus-ring focus:border-aws-orange resize-y"
              />
              {/* Section view */}
              <div className="mt-3 grid gap-2 sm:grid-cols-2">
                {generated.sections.map((s) => (
                  <div key={s.id} className="rounded-lg border border-token bg-[var(--card-2)]/40 p-2.5">
                    <div className="text-[10px] font-extrabold uppercase tracking-widest text-aws-orange">{s.label}</div>
                    <div className="text-[11px] text-muted mt-1 line-clamp-3 whitespace-pre-wrap">{s.body}</div>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
}

function Field({ k, v, wide }) {
  return (
    <div className={cn('flex flex-col', wide && 'col-span-2')}>
      <dt className="text-[10px] uppercase tracking-widest font-extrabold text-muted">{k}</dt>
      <dd className="text-xs font-semibold mt-0.5">{v || '—'}</dd>
    </div>
  );
}
